# Generated by Django 5.2.8 on 2025-11-11 08:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0008_company_average_price_alter_company_calculation_type_and_more'),
        ('menu', '0002_alter_fooditem_description'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیf')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'درصدی'), ('FIXED_AMOUNT', 'مبلغ ثابت')], max_length=20, verbose_name='نوع تخفیf')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار تخفیف')),
                ('max_usage_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد استفاده')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('max_usage_per_user', models.PositiveIntegerField(default=1, verbose_name='حداکثر استفاده برای هر کاربر')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حداقل مبلغ سفارش')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حداکثر مبلغ تخفیف')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('scope', models.CharField(choices=[('PUBLIC', 'عمومی'), ('PRIVATE', 'خصوصی')], default='PUBLIC', max_length=20, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicMenuDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام تخفیف')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='درصد تخفیف')),
                ('max_discount_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حداکثر تخفیف برای هر آیتم')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('show_on_menu', models.BooleanField(default=False, verbose_name='نمایش در منو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_companies', models.ManyToManyField(blank=True, related_name='dynamic_discounts', to='companies.company', verbose_name='شرکت\u200cهای مشمول')),
                ('applicable_items', models.ManyToManyField(blank=True, related_name='dynamic_discounts', to='menu.fooditem', verbose_name='آیتم\u200cهای مشمول')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.discountcode')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('discount_code', 'user', 'order')},
            },
        ),
    ]
