# Generated by Django 5.2.8 on 2025-11-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'درصدی'), ('FIXED_AMOUNT', 'مبلغ ثابت')], max_length=20, verbose_name='نوع تخفیف'),
        ),
    ]
