# Generated by Django 5.2.7 on 2025-10-22 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active_schedule',
            field=models.ForeignKey(blank=True, help_text='برنامه غذایی که برای کارمندان این شرکت نمایش داده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_companies', to='schedules.schedule'),
        ),
    ]
