# Generated by Django 5.2.7 on 2025-11-02 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_active_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_food_images', models.BooleanField(default=True)),
                ('show_food_prices', models.BooleanField(default=True)),
                ('admin_can_see_reports', models.BooleanField(default=True)),
                ('admin_can_access_surveys', models.BooleanField(default=True)),
                ('user_can_see_own_orders', models.BooleanField(default=True)),
                ('user_can_access_surveys', models.BooleanField(default=True)),
                ('user_has_wallet_access', models.BooleanField(default=True)),
                ('user_can_submit_tickets', models.BooleanField(default=False)),
                ('user_can_leave_comments', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='companies.company')),
            ],
        ),
    ]
