# Generated by Django 5.2.7 on 2025-11-05 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyconfiguration'),
        ('schedules', '0002_alter_schedule_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'شرکت', 'verbose_name_plural': 'شرکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='companyconfiguration',
            options={'verbose_name': 'تنظیمات شرکت', 'verbose_name_plural': 'تنظیمات شرکت\u200cها'},
        ),
        migrations.RemoveField(
            model_name='companyconfiguration',
            name='admin_can_access_surveys',
        ),
        migrations.RemoveField(
            model_name='companyconfiguration',
            name='admin_can_see_reports',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'منتشر شده'), ('DRAFT', 'پیش نویس')], default='DRAFT', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='admin_can_see_invoices',
            field=models.BooleanField(default=True, verbose_name='گزارش فاکتورها (ادمین)'),
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='admin_can_see_order_list',
            field=models.BooleanField(default=True, verbose_name='نمایش لیست سفارشات (ادمین)'),
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='admin_has_survey_access',
            field=models.BooleanField(default=True, verbose_name='دسترسی به نظرسنجی (ادمین)'),
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='admin_only_ordering',
            field=models.BooleanField(default=False, verbose_name='امکان سفارش فقط توسط ادمین'),
        ),
        migrations.AddField(
            model_name='companyconfiguration',
            name='allow_holidays',
            field=models.BooleanField(default=True, verbose_name='مجاز بودن سفارش در تعطیلات رسمی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='active_schedule',
            field=models.ForeignKey(blank=True, help_text='برنامه غذایی که برای کارمندان این شرکت نمایش داده می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_companies', to='schedules.schedule', verbose_name='برنامه غذایی فعال'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='شخص رابط'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='تلفن رابط'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='show_food_images',
            field=models.BooleanField(default=True, verbose_name='نمایش عکس غذا'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='show_food_prices',
            field=models.BooleanField(default=True, verbose_name='نمایش قیمت غذا'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='user_can_access_surveys',
            field=models.BooleanField(default=True, verbose_name='دسترسی به نظرسنجی (کاربر)'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='user_can_leave_comments',
            field=models.BooleanField(default=False, verbose_name='قابلیت ثبت کامنت (کاربر)'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='user_can_see_own_orders',
            field=models.BooleanField(default=True, verbose_name='مشاهده سفارشات من (کاربر)'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='user_can_submit_tickets',
            field=models.BooleanField(default=False, verbose_name='قابلیت ثبت تیکت (کاربر)'),
        ),
        migrations.AlterField(
            model_name='companyconfiguration',
            name='user_has_wallet_access',
            field=models.BooleanField(default=True, verbose_name='دسترسی به کیف پول (کاربر)'),
        ),
    ]
