# Generated by Django 5.2.7 on 2025-11-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='شناسه ملی'),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
