# Generated by Django 5.2.7 on 2025-11-09 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_national_id_company_notes'),
        ('schedules', '0002_alter_schedule_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='calculation_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع محاسبه'),
        ),
        migrations.AddField(
            model_name='company',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام هماهنگ کننده'),
        ),
        migrations.AddField(
            model_name='company',
            name='coordinator_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس هماهنگ کننده'),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_schedule',
            field=models.CharField(blank=True, default='هفتگی', max_length=100, verbose_name='ارسال فاکتور'),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدل پرداخت'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_deadline_hours',
            field=models.PositiveIntegerField(default=48, verbose_name='مهلت ثبت نام (ساعت قبل)'),
        ),
        migrations.AddField(
            model_name='company',
            name='settlement_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع تسویه'),
        ),
        migrations.AlterField(
            model_name='company',
            name='active_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_companies', to='schedules.schedule', verbose_name='برنامه غذایی فعال'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام ادمین'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس ادمین'),
        ),
    ]
