# Generated by Django 5.2.7 on 2025-11-10 06:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_calculation_type_company_coordinator_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='settlement_type',
        ),
        migrations.AddField(
            model_name='company',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'بدون تخفیف'), ('PERCENTAGE', 'درصدی'), ('FIXED', 'مبلغ ثابت')], default='NONE', max_length=20, verbose_name='نوع تخفیف'),
        ),
        migrations.AddField(
            model_name='company',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='مقدار تخفیف (درصد یا مبلغ ثابت)'),
        ),
        migrations.AddField(
            model_name='company',
            name='rounding_amount',
            field=models.CharField(choices=[('NONE', 'بدون رند کردن'), ('HUNDRED', 'نزدیک\u200cترین ۱۰۰'), ('FIVE_HUNDRED', 'نزدیک\u200cترین ۵۰۰'), ('THOUSAND', 'نزدیک\u200cترین ۱۰۰۰')], default='NONE', max_length=20, verbose_name='رند کردن مبلغ (برای تخفیف درصدی)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='invoice_schedule',
            field=models.CharField(choices=[('WEEKLY', 'هفتگی'), ('BIWEEKLY', 'دو هفتگی'), ('MONTHLY', 'ماهانه')], default='WEEKLY', max_length=20, verbose_name='دوره ارسال فاکتور'),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_model',
            field=models.CharField(choices=[('ONLINE', 'آنلاین'), ('INVOICE', 'ارسال فاکتور')], default='ONLINE', max_length=20, verbose_name='مدل پرداخت'),
        ),
    ]
