# Generated by Django 5.2.7 on 2025-11-10 07:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_company_settlement_type_company_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='مبلغ میانگین (در صورت انتخاب)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='calculation_type',
            field=models.CharField(choices=[('FLUID', 'سیال'), ('AVERAGE', 'میانگین')], default='FLUID', max_length=20, verbose_name='نوع محاسبه قیمت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rounding_amount',
            field=models.CharField(choices=[('NONE', 'بدون رند کردن'), ('HUNDRED', 'نزدیک\u200cترین ۱۰۰'), ('FIVE_HUNDRED', 'نزدیک\u200cترین ۵۰۰'), ('THOUSAND', 'نزدیک\u200cترین ۱۰۰۰')], default='NONE', max_length=20, verbose_name='رند کردن مبلغ'),
        ),
    ]
