# Generated by Django 5.2.7 on 2025-10-19 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLACED', 'ثبت شده'), ('CONFIRMED', 'تایید شده'), ('PREPARING', 'در حال آماده\u200cسازی'), ('DELIVERED', 'تحویل داده شده'), ('CANCELED', 'لغو شده')], default='PLACED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='schedules.dailymenu')),
                ('food_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menu.fooditem')),
                ('side_dishes', models.ManyToManyField(blank=True, related_name='orders', to='menu.sidedish')),
            ],
        ),
    ]
